apiVersion: v1
kind: Service
metadata:
  name: chronograf-jmeter
  labels:
    app: chronograf-jmeter
spec:
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: chronograf-jmeter
  type: LoadBalancer
