apiVersion: v1
kind: Service
metadata:
  name: jmeter-influxdb
  labels:
    app: influxdb-jmeter
spec:
  ports:
    - port: 8083
      name: http
      targetPort: 8083
    - port: 8086
      name: api
      targetPort: 8086
    - port: 2003
      name: graphite
      targetPort: 2003
    - port: 22
      name: ssh
      targetPort: 22
    - port: 8888
      name: chronograf
      targetPort: 8888
  selector:
    app: influxdb-jmeter
  type: LoadBalancer
